version: '3.8'

networks:
  default:
    driver: ${NETWORKS_DRIVER}

services:
### nginx ##############################
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/ssl/:/ssl:rw
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - gitea
      - drone
    restart: always
    networks:
      - default
### gitea ######################
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    ports:
      - "${GITEA_SSH_PORT}:22"
    volumes:
      - ./data/gitea:/data
    environment:
      - TZ=Asia/Shanghai
    expose:
    - "3000"
    networks:
      - default
### drone ######################
  drone:
    image: drone/drone:latest
    container_name: drone
    volumes:
      - ./data/drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "9000"
      - "80"
      - "443"
    restart: always
    environment:
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_GITEA_SERVER=http://${GITEA_HOST}
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${DRONE_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=http
      - TZ=Asia/Shanghai
    networks:
    - default
### drone-agent ######################
  drone-agent:
    image: drone/agent:latest
    container_name: drone-agent
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - DRONE_DEBUG=false
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_RPC_SERVER=http://${DRONE_SERVER_HOST}:9000
      - DRONE_RPC_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=5
      - TZ=Asia/Shanghai
    networks:
    - default